1 d11ex1: d11ex1.o d11ex2 d11ex3 d11ex2b
		gcc d11ex1.o -o d11ex1
2 d11ex1.o: d11ex1.c 
		gcc d11ex1.c -c 

3 d11ex2: d11ex2.o 
		gcc d11ex2.o -o d11ex2
4 d11ex2.o: d11ex2.c 
		gcc d11ex2.c -c 
		
5 d11ex3: d11ex3.o 
		gcc d11ex3.o -o d11ex3
6 d11ex3.o: d11ex3.c 
		gcc d11ex3.c -c 
		
		
7 .PHONY: clean.o 

8 clean.o:
		rm -rf *.o
		
9 d11ex2b: d11ex2b.o 
		gcc d11ex2b.o -o d11ex2b
10 d11ex2b.o: d11ex2b.c 
		gcc d11ex2b.c -c 
		
		
		
		





