1 d6ex1: d6ex1.o d6ex1.o parsing.o dinamic.o
		gcc d6ex1.o parsing.o dinamic.o -o d6ex1 -g
2 d6ex1.o: d6ex1.c main.h
		gcc d6ex1.c -c -g
3 parsing.o: parsing.c parsing.h
		gcc parsing.c -c -g
4 dinamic.o: dinamic.c dinamic.h
		gcc dinamic.c -c -g


